### ISSUE TITLE
Update protostuff to 1.5.2

### ISSUE THREAD

**Issue by dyu** [MaxLeap/vertx-rpc#12]
Hello guys,

If your dataset has a lot of collections/maps, updating to 1.5.2 would instantly improve the performance, especially on deser.

Cheers!

**Comment by stream1984** [comment]
Got it, we will update this project in two weeks.

**Comment by dyu** [comment]
Cool.  Now I'm curious why exactly two weeks (-:
Is this project deployed in production at maxleap?

Thanks

**Comment by stream1984** [comment]
We will refactor this project and this will spent one week, then we have to deploy it on our test ENV before deploy it to production.
Yes, we have deployed this project at maxleap.
