### ISSUE TITLE
Latest version on Maven is 3.1.1

### ISSUE THREAD

**Issue by vophihung** [MaxLeap/vertx-rpc#13]
Please update it

**Comment by stream1984** [comment]
We have update it to maven repos, and oss is indexing it, could be download by maven in two days. :)

**Comment by vophihung** [comment]
![screenshot from 2016-11-07 09-03-56](https://cloud.githubusercontent.com/assets/3926661/20044187/3bbee0a6-a4c9-11e6-9a0b-60ee80c7ca67.png)
I don't see anything in 3.3.3
