### ISSUE TITLE
No .jar file in 3.3.3

### ISSUE THREAD

**Issue by vophihung** [MaxLeap/vertx-rpc#14]
![screenshot from 2016-11-07 09-03-56](https://cloud.githubusercontent.com/assets/3926661/20044218/7947feb2-a4c9-11e6-92ab-9788fbd99e8f.png)

I tried to delete and download again but nothing happens (see attachment)

**Comment by stream1984** [comment]
Sorry for that, and 3.3.3 release have failed. I have release a new version. Does 3.1.1 can not work for you!

**Comment by vophihung** [comment]
Thank you

Just want to have latest version :p

**Comment by stream1984** [comment]
Hi @vophihung 
3.3.4 have validate in maven repos.
