### ISSUE TITLE
Missing file jar in 3.3.4

### ISSUE THREAD

**Issue by vophihung** [MaxLeap/vertx-rpc#15]
![screenshot from 2016-11-16 09-05-44](https://cloud.githubusercontent.com/assets/3926661/20332037/e4baccc4-abdb-11e6-82af-82fe7c16bb4c.png)

**Comment by stream1984** [comment]
Hi
It's true, but  vertx-rpc-3.3.4.jar is exist in my repo, i have send mail to maven central to figure out what happend

**Comment by stream1984** [comment]
Hi
can you confirm that vertx-rpc-3.3.6.jar is available.
http://central.maven.org/maven2/as/leap/vertx-rpc/3.3.6/

**Comment by vophihung** [comment]
![screenshot from 2016-11-22 14-31-57](https://cloud.githubusercontent.com/assets/3926661/20514767/7c9ac5d8-b0c0-11e6-92e8-2ac15fefd4fc.png)
