### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by jclohmann** [MaxLeap/vertx-rpc#16]
Hi, I would like to use your project in a commercial web-application, but it I couldn't find a license-file.

Can you select a license and add it to the project? (Preferably one that allows commercial usage.)

**Comment by Mart-Bogdan** [comment]
pom. xml
```xml
<licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
```
